site_name: Awesome Software Engineer
site_url: https://awesomesoftwareengineer.com
site_description: Share practical software engineering skills including backend, architecture, and engineering mindset
docs_dir: 
repo_name: raychongtk/awesome-software-engineer
repo_url: https://github.com/raychongtk/awesome-software-engineer
theme: 
  name: material 
  extra_css: [extra.css]
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.top
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
  palette:
    primary: black
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
- Newsletter: https://blog.awesomesoftwareengineer.com
- Home: https://awesomesoftwareengineer.com
- Architecture:
  - Understand Observability: architecture/understand-observability.md
  - Log Monitoring and Alerting: architecture/log-monitoring-and-alerting.md
  - 4 Popular Cache Patterns: architecture/4-popular-cache-patterns.md
  - Cache Delete Strategy of Cache-aside Pattern: architecture/cache-delete-strategy.md
  - Handling Jobs Efficiently: architecture/handling-job-efficiently.md
  - API vs Webhook: architecture/api-vs-webhook.md
  - Why Do We Need Webhook?: architecture/why-do-we-need-webhook?.md
  - Understand Software Complexity: architecture/understand-software-complexity.md
  - Understand System Bottleneck: architecture/understand-system-bottleneck.md
  - What is Event-driven Architecture?: architecture/what-is-event-driven-architecture?.md
  - Payment Event-driven Architecture: architecture/event-driven-payment-architecture.md
  - Boost API Read Performance by 10x with Cache: architecture/boost-api-read-performance-by-10x-with-cache.md
  - How Does Lalamove Scale Its Communication Platform?: architecture/how-does-lalamove-scale-its-communication-platform?.md
  - Redeisn Your Development Workflow with Mock Service: architecture/mock-service.md
  - Architecting for Simplicity: architecture/architecting-for-simplicity.md
  - Architecture Mystery: architecture/architecture-mystery.md
  - Why Do We Need Architecture?: architecture/why-do-we-need-architecture?.md
  - Design for Adaptability: architecture/design-for-adaptability.md
  - Exploring Architetcure - What Does It Really Mean?: architecture/exploring-architetcure.md
  - Consistency and Availability: architecture/consistency-vs-availability.md
  - Pub/Sub Practical Guide - Use Case: architecture/pubsub-practical-guide-use-case.md
  - Pub/Sub Practical Guide - Trade Off: architecture/pubsub-practical-guide-trade-off.md
- Microservices: microservices.md
- Software Design:
  - Prefer Duplication over Wrong Abstraction: software-design/prefer-duplication-over-wrong-abstraction.md
  - Simple is the best: software-design/simple-is-the-best.md
  - Choose the right way to create objects: software-design/choose-the-right-way-to-create-objects.md
  - Build a complex object: software-design/build-a-complex-object.md
  - Gracefully handle dynamic behaviors in the same category: software-design/gracefully-handle-dynamic-behavior.md
  - Avoid throwing exception as control flow: software-design/avoid-throwing-expcetion-as-control-flow.md
  - Backward compatible thinking: software-design/backward-compatible-thinking.md
  - Backward compatibility trade off: software-design/backward-compatibility-trade-off.md
  - Design Space Optimization: software-design/design-space-optimization.md
- API Design:
  - Everything about RESTful API: api-design/everything-about-restful-api.md
  - Let UI Drive API Design: api-design/let-ui-drive-api-design.md
  - Designing API with the Right Granularity: api-design/designing-api-with-the-right-granularity.md
  - How to Handle API Backward Compatibility?: api-design/how-to-handle-api-backward-compatibility?.md
  - Improve Performance When Retrieving Large Dataset: api-design/improve-performance-when-retrieving-large-dataset.md
  - Do You Use Pagination Right?: api-design/do-you-use-pagination-right?.md
  - Enhancing API Performance Through Batch Requests: api-design/optimize-api-via-batch-requests.md
- Security: security.md
- General Software Engineering: general-software-engineering.md
- Code Review:
  - Code Author Journey: code-review/author-journey.md
  - Reviewer Journey: code-review/reviewer-journey.md

copyright: 2023 <a href="https://github.com/raychongtk">Ray Chong</a>.
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/raychongtk
    - icon: fontawesome/brands/github-alt
      link: https://github.com/raychongtk