site_name: Awesome Software Engineer
site_url: https://awesomesoftwareengineer.com
site_description: Share practical software engineering skills including backend, architecture, and engineering mindset
docs_dir: 
repo_name: raychongtk/awesome-software-engineer
repo_url: https://github.com/raychongtk/awesome-software-engineer
edit_uri: edit/main/docs/
theme: 
  name: material 
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
- Microservices: microservices.md
- Architecture: architecture.md
- Coding and Software Design: coding-and-software-design.md
- API Design: api-design.md
- Security: security.md
- General Software Engineering: general-software-engineering.md

copyright: 2023 <a href="https://github.com/raychongtk">Ray Chong</a>.
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/raychongtk
    - icon: fontawesome/brands/github-alt
      link: https://github.com/raychongtk